server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy reverso opcional si quisieras evitar CORS en producción
    # location /api/ {
    #     proxy_pass http://api_backend:8080/;
    # }
}