name: smartfin

services:
  api_backend:
    build:
      context: ../../apps/api/smartfin_api
      dockerfile: Dockerfile
    container_name: smartfin-api-backend
    environment:
      TZ: ${SF_TZ:-America/Guayaquil}
      SPRING_PROFILES_ACTIVE: ${SF_SPRING_PROFILE:-local}
      # CORRECCIÓN: Usamos las variables nativas de Spring Boot para forzar la conexión correcta
      SPRING_DATASOURCE_URL: jdbc:postgresql://smartfin-postgres-oper:5432/${SF_OPER_DB:-smartfin_operacional}
      SPRING_DATASOURCE_USERNAME: ${SF_OPER_USER:-smartfin}
      SPRING_DATASOURCE_PASSWORD: ${SF_OPER_PASSWORD:-smartfin123}
      # Inyectamos también el secreto JWT que faltaba
      SMARTFIN_JWT_SECRETO: ${SF_JWT_SECRETO:-secreto_por_defecto_para_desarrollo}
    ports:
      - "${SF_API_PORT:-8080}:8080"
    networks:
      - smartfin_red

  # servicio_inteligencia_artificial:
  #   build:
  #     context: ./ai
  #     dockerfile: Dockerfile
  #   container_name: smartfin-servicio-ia
  #   environment:
  #     TZ: ${SF_TZ:-America/Guayaquil}
  #     BASE_DATOS_URL: ${SF_OPER_PG_URL:-postgresql://smartfin:${SF_OPER_PASSWORD:-smartfin123}@postgres_operacional:5432/smartfin_oper}
  #   ports:
  #     - "${SF_IA_PORT:-8000}:8000"
  #   networks:
  #     - smartfin_red

  aplicacion_frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    container_name: smartfin-frontend
    environment:
      TZ: ${SF_TZ:-America/Guayaquil}
      API_URL: ${SF_API_URL_PUBLICA:-http://localhost:8080}
    ports:
      - "${SF_FRONTEND_PORT:-4200}:80"
    networks:
      - smartfin_red
    depends_on:
      - api_backend

networks:
  smartfin_red:
    external: true
    name: smartfin_smartfin_red
